// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID               int64         `json:"id"`
	Salt             []byte        `json:"salt"`
	Email            string        `json:"email"`
	Password         []byte        `json:"password"`
	FailedLoginCount sql.NullInt32 `json:"failed_login_count"`
	LastLoginAt      sql.NullTime  `json:"last_login_at"`
	CreatedAt        sql.NullTime  `json:"created_at"`
}

type Session struct {
	Uuid         string       `json:"uuid"`
	AccountID    int64        `json:"account_id"`
	RefreshToken string       `json:"refresh_token"`
	UserAgent    string       `json:"user_agent"`
	ClientIp     string       `json:"client_ip"`
	IsBlocked    bool         `json:"is_blocked"`
	ExpireAt     time.Time    `json:"expire_at"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
